/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'UserRegistration': ApiRouteHandler<{ email: string; password: string; name: string }, ApiResponse<201, { user: { id: string; email: string; name: string }; token?: string }> | ApiResponse<400, { error: string }> | ApiResponse<409, { error: string }>, { topic: 'user.registration.process'; data: { email: string; password: string; name: string } }>
    'GetMe': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { id: string; email: string; name: string; emailVerified?: boolean; createdAt?: string; updatedAt?: string } }> | ApiResponse<401, { error: string }>, never>
    'UserLogin': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { user: { id: string; email: string; name: string }; token?: string }> | ApiResponse<401, { error: string }>, { topic: 'user.login.process'; data: { email: string; password: string; ipAddress?: string } }>
    'LogWelcomeEmailSent': EventHandler<{ userId: string; email: string; name: string; sentAt: string }, never>
    'SendWelcomeEmail': EventHandler<{ userId: string; email: string; name: string; timestamp: string }, { topic: 'user.welcome-email.sent'; data: { userId: string; email: string; name: string; sentAt: string } }>
    'ProcessRegistration': EventHandler<{ email: string; password: string; name: string }, { topic: 'user.registration.completed'; data: { userId: string; email: string; name: string; token: string | unknown; timestamp: string } } | { topic: 'user.registration.failed'; data: { email: string; name: string; error: string; timestamp: string } }>
    'LogRegistrationFailed': EventHandler<{ email: string; name: string; error: string; timestamp: string }, never>
    'LogRegistrationCompleted': EventHandler<{ userId: string; email: string; name: string; token: string | unknown; timestamp: string }, { topic: 'user.welcome-email.process'; data: { userId: string; email: string; name: string; timestamp: string } }>
    'ProcessLogin': EventHandler<{ email: string; password: string; ipAddress?: string }, { topic: 'user.login.completed'; data: { userId: string; email: string; name: string; token: string | unknown; ipAddress: string; timestamp: string } } | { topic: 'user.login.failed'; data: { email: string; error: string; ipAddress: string; timestamp: string } }>
    'LogLoginFailed': EventHandler<{ email: string; error: string; ipAddress: string; timestamp: string }, never>
    'LogLoginCompleted': EventHandler<{ userId: string; email: string; name: string; token: string | unknown; ipAddress: string; timestamp: string }, never>
    'LogApiKeyFailed': EventHandler<{ userId: string; name: string; error: string; timestamp: string } | { userId: string; apiKeyId: string; error: string; timestamp: string }, never>
    'ProcessDeleteApiKey': EventHandler<{ userId: string; apiKeyId: string }, { topic: 'api-key.deletion.completed'; data: { apiKeyId: string; userId: string; timestamp: string } } | { topic: 'api-key.deletion.failed'; data: { userId: string; name: string; error: string; timestamp: string } | { userId: string; apiKeyId: string; error: string; timestamp: string } }>
    'LogApiKeyDeleted': EventHandler<{ apiKeyId: string; userId: string; timestamp: string }, never>
    'ProcessCreateApiKey': EventHandler<{ userId: string; name: string; expiresIn?: number }, { topic: 'api-key.creation.completed'; data: { apiKeyId: string; key: string; userId: string; name: string | unknown; prefix: string | unknown; expiresAt: string | unknown; timestamp: string } } | { topic: 'api-key.creation.failed'; data: { userId: string; name: string; error: string; timestamp: string } | { userId: string; apiKeyId: string; error: string; timestamp: string } }>
    'LogApiKeyCreated': EventHandler<{ apiKeyId: string; key: string; userId: string; name: string | unknown; prefix: string | unknown; expiresAt: string | unknown; timestamp: string }, never>
    'ListApiKeys': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, Array<{ id: string; name: string; prefix: string; expiresAt?: string; createdAt: string; lastRequest?: string }>> | ApiResponse<401, { error: string }>, never>
    'DeleteApiKey': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean }> | ApiResponse<401, { error: string }> | ApiResponse<403, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'api-key.deletion.process'; data: { userId: string; apiKeyId: string } }>
    'CreateApiKey': ApiRouteHandler<{ name: string; expiresIn?: number }, ApiResponse<201, { id: string; key: string; name: string; prefix: string; expiresAt?: string }> | ApiResponse<401, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'api-key.creation.process'; data: { userId: string; name: string; expiresIn?: number } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
  }
    
}